export const card = [
  {
    id: 0,
    Raised: "46303",
    Goals: "95000",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
  {
    id: 1,
    Raised: "54303",
    Goals: "95679",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
  {
    id: 2,
    Raised: "34303",
    Goals: "59000",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
  {
    id: 3,
    Raised: "38303",
    Goals: "54000",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
  {
    id: 4,
    Raised: "38303",
    Goals: "54000",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
  {
    id: 534,
    Raised: "38303",
    Goals: "54000",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
  {
    id: 2346,
    Raised: "38303",
    Goals: "54000",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
  {
    id: 5,
    Raised: "38303",
    Goals: "54000",
    des: "Help sarah go to primary school next year",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
  },
];
export const hover = [
  {
    id: 0,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    monthyear: "june 2023",
    Date: "31",
    time: "10:00 AM - 07:00 PM",
    place: "Russian & Turkish Baths",
    title: "How do you know if a stock will make you money over time",
  },
];
export const news = [
  {
    id: 0,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    date: "August 12 2019",
    Title: "First child dies of Ebola in new outbreak in Uganda",
    des: "We help families raise funds for their adoptions by telling their story to a larger ...",
  },
  {
    id: 1,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    date: "August 12 2019",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    Title: "First child dies of Ebola in new outbreak in Uganda",
    des: "We help families raise funds for their adoptions by telling their story to a larger ...",
  },
  {
    id: 2,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    date: "August 12 2019",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    Title: "First child dies of Ebola in new outbreak in Uganda",
    des: "We help families raise funds for their adoptions by telling their story to a larger ...",
  },
  {
    id: 3,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    date: "August 12 2019",
    Title: "First child dies of Ebola in new outbreak in Uganda",
    des: "We help families raise funds for their adoptions by telling their story to a larger ...",
  },
  {
    id: 4,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    date: "August 12 2019",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    Title: "First child dies of Ebola in new outbreak in Uganda",
    des: "We help families raise funds for their adoptions by telling their story to a larger ...",
  },
  {
    id: 5,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    date: "August 12 2019",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    Title: "First child dies of Ebola in new outbreak in Uganda",
    des: "We help families raise funds for their adoptions by telling their story to a larger ...",
  },
];
export const testi = [
  {
    id: 0,
    cover:
      "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTXMMO8k4M55zkMLrWN_cSQ61L5v8SZQrBY31DdyuIfwCshamFhcKVtsWAL8odCJOw0wxLUrrWw9wj5-CY",
    Title: "Sunita Williams",
    quote:
      "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/icon-quote.png",
    desi: "Astronaut",
    bigdes:
      "Everything we do centres on protecting you and your business from risk ,Peace of mind so you can focus on what’s important",
  },
  {
    id: 1,
    cover:
      "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTXMMO8k4M55zkMLrWN_cSQ61L5v8SZQrBY31DdyuIfwCshamFhcKVtsWAL8odCJOw0wxLUrrWw9wj5-CY",
    png: "../src/assets/unlink.png",
    Title: "Sunita Williams",
    quote:
      "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/icon-quote.png",
    desi: "Astronaut",
    bigdes:
      "Everything we do centres on protecting you and your business from risk ,Peace of mind so you can focus on what’s important",
  },
  {
    id: 2,
    cover:
      "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTXMMO8k4M55zkMLrWN_cSQ61L5v8SZQrBY31DdyuIfwCshamFhcKVtsWAL8odCJOw0wxLUrrWw9wj5-CY",
    png: "../src/assets/unlink.png",
    Title: "Sunita Williams",
    quote:
      "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/icon-quote.png",
    desi: "Astronaut",
    bigdes:
      "Everything we do centres on protecting you and your business from risk ,Peace of mind so you can focus on what’s important",
  },
  // {
  //   id: 3,
  //   cover:
  //     "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTXMMO8k4M55zkMLrWN_cSQ61L5v8SZQrBY31DdyuIfwCshamFhcKVtsWAL8odCJOw0wxLUrrWw9wj5-CY",
  //   png: "../src/assets/unlink.png",
  //   Title: "Sunita Williams",
  //   quote:
  //     "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/icon-quote.png",
  //   desi: "Astronaut",
  //   bigdes:
  //     "Everything we do centres on protecting you and your business from risk ,Peace of mind so you can focus on what’s important",
  // },
  // {
  //   id: 4,
  //   cover:
  //     "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTXMMO8k4M55zkMLrWN_cSQ61L5v8SZQrBY31DdyuIfwCshamFhcKVtsWAL8odCJOw0wxLUrrWw9wj5-CY",
  //   png: "../src/assets/unlink.png",
  //   Title: "Sunita Williams",
  //   quote:
  //     "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/icon-quote.png",
  //   desi: "Astronaut",
  //   bigdes:
  //     "Everything we do centres on protecting you and your business from risk ,Peace of mind so you can focus on what’s important",
  // },
  // {
  //   id: 5,
  //   cover:
  //     "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTXMMO8k4M55zkMLrWN_cSQ61L5v8SZQrBY31DdyuIfwCshamFhcKVtsWAL8odCJOw0wxLUrrWw9wj5-CY",
  //   png: "../src/assets/unlink.png",
  //   Title: "Sunita Williams",
  //   quote:
  //     "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/icon-quote.png",
  //   desi: "Astronaut",
  //   bigdes:
  //     "Everything we do centres on protecting you and your business from risk ,Peace of mind so you can focus on what’s important",
  // },
];
export const sponser = [
  {
    id: 0,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/donation.png",
    Name: "Volunteer",
  },
  {
    id: 1,
    cover: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    Name: "Help Life",
  },
  {
    id: 2,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/ballons.png",
    Name: "Give Thoughtfully",
  },
  {
    id: 3,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/people.png",
    Name: "Donate Now",
  },
];
export const images = [
  {
    id: 0,
    img: "../src/assets/im2.jpg",
  },
  {
    id: 1,
    img: "../src/assets/im3.jpg",
  },
  {
    id: 2,
    img: "../src/assets/im4.jpg",
  },
  {
    id: 3,
    img: "../src/assets/im5.jpg",
  },
  {
    id: 4,
    img: "../src/assets/im2.jpg",
  },
  {
    id: 5,
    img: "../src/assets/im3s.jpg",
  },
];

export const work = [
  {
    id: "0",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Healthcare",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "red",
  },
  {
    id: "1",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Nutrition",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "#b250d2",
  },
  {
    id: "2",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Education",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "#ef884c",
  },
  {
    id: "3",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Livelihood",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "#2780ba",
  },
  {
    id: "4",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Livelihood",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "#b250d2",
  },
  {
    id: "5",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Livelihood",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "#efc94c",
  },
  {
    id: "6",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Livelihood",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "#00baa3",
  },
  {
    id: "7",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    title: "Livelihood",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/help.png",
    color: "#d55342",
  },
];
export const donation = [
  {
    id: "0",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    btncol: "#b250d2",
    title: "Child Support",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend.",
    barcol: "#b250d2",
    Goals: "25000",
    Raised: "5600",
    btn2col: "#b250d2",
  },
  {
    id: "1",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    btncol: "#ef884c",
    title: "Child Support",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend.",
    barcol: "#ef884c",
    Goals: "35000",
    Raised: "15600",
    btn2col: "#ef884c",
  },
  {
    id: "2",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    btncol: "#2780ba",
    title: "Child Support",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend.",
    barcol: "#2780ba",
    Goals: "155000",
    Raised: "85600",
    btn2col: "#2780ba",
  },
  {
    id: "3",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    btncol: "#d55342",
    title: "Child Support",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend",
    barcol: "#d55342",
    Goals: "55000",
    Raised: "25600",
    btn2col: "#d55342",
  },
  {
    id: "4",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    btncol: "#00baa3",
    title: "Child Support",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend.",
    barcol: "#00baa3",
    Goals: "525000",
    Raised: "225600",
    btn2col: "#00baa3",
  },
  {
    id: "5",
    img: "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    btncol: "#efc94c",
    title: "Child Support",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend.",
    barcol: "#efc94c",
    Goals: "51000",
    Raised: "42600",
    btn2col: "#efc94c",
  },
];
export const Eventcard = [
  {
    id: 0,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    monthyear: "june 2023",
    Date: 22,
    StartEnd: "Start: June 18, 2023 | End: June 19, 2023",

    time: "10:00 AM - 07:00 PM",
    place: "Russian & Turkish Baths",
    title: "How do you know if a stock will make you money over time",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend nd ac tellus fringilla eleifend aksdh.",
  },
  {
    id: 1,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    monthyear: "june 2023",
    Date: 22,
    StartEnd: "Start: June 18, 2023 | End: June 19, 2023",

    time: "10:00 AM - 07:00 PM",
    place: "Russian & Turkish Baths",
    title: "How do you know if a stock will make you money over time",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend ac tellus fringilla eleifend aksdh",
  },
  {
    id: 2,
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    monthyear: "june 2023",
    Date: 22,
    StartEnd: "Start: June 18, 2023 | End: June 19, 2023",

    time: "10:00 AM - 07:00 PM",
    place: "Russian & Turkish Baths",
    title: "How do you know if a stock will make you money over time",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna ac tellus fringilla eleifend. nd ac tellus fringilla eleifend aksdh",
  },
];

export const logos = [
  {
    id: "0",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/awb-1.png",
  },
  {
    id: "1",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/nasa-1.png",
  },
  {
    id: "2",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/oxford-2.png",
  },
  {
    id: "3",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/iau-logo-2.png",
  },
  {
    id: "4",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/UIts-Logo-1.png",
  },
  {
    id: "5",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/Akhok-1.png",
  },
  {
    id: "6",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/EarthKAM-1.png",
  },
  {
    id: "7",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/novodya-1.png",
  },
  {
    id: "8",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/Space-Arcade-Logo-1.png",
  },
  {
    id: "9",
    img: "https://space-foundation.org/wp-content/uploads/2022/08/ksc-1.png",
  },
];
export const cards = [
  {
    id: "0",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    title: "How do you know if a stock will make you money over time.",
    Start: "July 31, 2019",
    End: "July 31, 2020",
    Address: "Russian & Turkish Baths",
  },
  {
    id: "1",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    title: "How do you know if a stock will make you money over time.",
    Start: "July 31, 2019",
    End: "July 31, 2020",
    Address: "Russian & Turkish Baths",
  },
  {
    id: "2",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    title: "How do you know if a stock will make you money over time.",
    Start: "July 31, 2019",
    End: "July 31, 2020",
    Address: "Russian & Turkish Baths",
  },
  {
    id: "3",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    title: "How do you know if a stock will make you money over time.",
    Start: "July 31, 2019",
    End: "July 31, 2020",
    Address: "Russian & Turkish Baths",
  },
  {
    id: "4",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    title: "How do you know if a stock will make you money over time.",
    Start: "July 31, 2019",
    End: "July 31, 2020",
    Address: "Russian & Turkish Baths",
  },
  {
    id: "5",
    cover:
      "https://demoapus2.com/crowdngo/wp-content/uploads/2019/08/charity_01-670x453.jpg",
    png: "https://demoapus2.com/crowdngo/wp-content/themes/crowdngo/images/unlink.png",
    title: "How do you know if a stock will make you money over time.",
    Start: "July 31, 2019",
    End: "July 31, 2020",
    Address: "Russian & Turkish Baths",
  },
];



export const countries = [
  { code: 'AD', label: 'Andorra', phone: '376' },
  {
    code: 'AE',
    label: 'United Arab Emirates',
    phone: '971',
  },
  { code: 'AF', label: 'Afghanistan', phone: '93' },
  {
    code: 'AG',
    label: 'Antigua and Barbuda',
    phone: '1-268',
  },
  { code: 'AI', label: 'Anguilla', phone: '1-264' },
  { code: 'AL', label: 'Albania', phone: '355' },
  { code: 'AM', label: 'Armenia', phone: '374' },
  { code: 'AO', label: 'Angola', phone: '244' },
  { code: 'AQ', label: 'Antarctica', phone: '672' },
  { code: 'AR', label: 'Argentina', phone: '54' },
  { code: 'AS', label: 'American Samoa', phone: '1-684' },
  { code: 'AT', label: 'Austria', phone: '43' },
  {
    code: 'AU',
    label: 'Australia',
    phone: '61',
    suggested: true,
  },
  { code: 'AW', label: 'Aruba', phone: '297' },
  { code: 'AX', label: 'Alland Islands', phone: '358' },
  { code: 'AZ', label: 'Azerbaijan', phone: '994' },
  {
    code: 'BA',
    label: 'Bosnia and Herzegovina',
    phone: '387',
  },
  { code: 'BB', label: 'Barbados', phone: '1-246' },
  { code: 'BD', label: 'Bangladesh', phone: '880' },
  { code: 'BE', label: 'Belgium', phone: '32' },
  { code: 'BF', label: 'Burkina Faso', phone: '226' },
  { code: 'BG', label: 'Bulgaria', phone: '359' },
  { code: 'BH', label: 'Bahrain', phone: '973' },
  { code: 'BI', label: 'Burundi', phone: '257' },
  { code: 'BJ', label: 'Benin', phone: '229' },
  { code: 'BL', label: 'Saint Barthelemy', phone: '590' },
  { code: 'BM', label: 'Bermuda', phone: '1-441' },
  { code: 'BN', label: 'Brunei Darussalam', phone: '673' },
  { code: 'BO', label: 'Bolivia', phone: '591' },
  { code: 'BR', label: 'Brazil', phone: '55' },
  { code: 'BS', label: 'Bahamas', phone: '1-242' },
  { code: 'BT', label: 'Bhutan', phone: '975' },
  { code: 'BV', label: 'Bouvet Island', phone: '47' },
  { code: 'BW', label: 'Botswana', phone: '267' },
  { code: 'BY', label: 'Belarus', phone: '375' },
  { code: 'BZ', label: 'Belize', phone: '501' },
  {
    code: 'CA',
    label: 'Canada',
    phone: '1',
    suggested: true,
  },
  {
    code: 'CC',
    label: 'Cocos (Keeling) Islands',
    phone: '61',
  },
  {
    code: 'CD',
    label: 'Congo, Democratic Republic of the',
    phone: '243',
  },
  {
    code: 'CF',
    label: 'Central African Republic',
    phone: '236',
  },
  {
    code: 'CG',
    label: 'Congo, Republic of the',
    phone: '242',
  },
  { code: 'CH', label: 'Switzerland', phone: '41' },
  { code: 'CI', label: "Cote d'Ivoire", phone: '225' },
  { code: 'CK', label: 'Cook Islands', phone: '682' },
  { code: 'CL', label: 'Chile', phone: '56' },
  { code: 'CM', label: 'Cameroon', phone: '237' },
  { code: 'CN', label: 'China', phone: '86' },
  { code: 'CO', label: 'Colombia', phone: '57' },
  { code: 'CR', label: 'Costa Rica', phone: '506' },
  { code: 'CU', label: 'Cuba', phone: '53' },
  { code: 'CV', label: 'Cape Verde', phone: '238' },
  { code: 'CW', label: 'Curacao', phone: '599' },
  { code: 'CX', label: 'Christmas Island', phone: '61' },
  { code: 'CY', label: 'Cyprus', phone: '357' },
  { code: 'CZ', label: 'Czech Republic', phone: '420' },
  {
    code: 'DE',
    label: 'Germany',
    phone: '49',
    suggested: true,
  },
  { code: 'DJ', label: 'Djibouti', phone: '253' },
  { code: 'DK', label: 'Denmark', phone: '45' },
  { code: 'DM', label: 'Dominica', phone: '1-767' },
  {
    code: 'DO',
    label: 'Dominican Republic',
    phone: '1-809',
  },
  { code: 'DZ', label: 'Algeria', phone: '213' },
  { code: 'EC', label: 'Ecuador', phone: '593' },
  { code: 'EE', label: 'Estonia', phone: '372' },
  { code: 'EG', label: 'Egypt', phone: '20' },
  { code: 'EH', label: 'Western Sahara', phone: '212' },
  { code: 'ER', label: 'Eritrea', phone: '291' },
  { code: 'ES', label: 'Spain', phone: '34' },
  { code: 'ET', label: 'Ethiopia', phone: '251' },
  { code: 'FI', label: 'Finland', phone: '358' },
  { code: 'FJ', label: 'Fiji', phone: '679' },
  {
    code: 'FK',
    label: 'Falkland Islands (Malvinas)',
    phone: '500',
  },
  {
    code: 'FM',
    label: 'Micronesia, Federated States of',
    phone: '691',
  },
  { code: 'FO', label: 'Faroe Islands', phone: '298' },
  {
    code: 'FR',
    label: 'France',
    phone: '33',
    suggested: true,
  },
  { code: 'GA', label: 'Gabon', phone: '241' },
  { code: 'GB', label: 'United Kingdom', phone: '44' },
  { code: 'GD', label: 'Grenada', phone: '1-473' },
  { code: 'GE', label: 'Georgia', phone: '995' },
  { code: 'GF', label: 'French Guiana', phone: '594' },
  { code: 'GG', label: 'Guernsey', phone: '44' },
  { code: 'GH', label: 'Ghana', phone: '233' },
  { code: 'GI', label: 'Gibraltar', phone: '350' },
  { code: 'GL', label: 'Greenland', phone: '299' },
  { code: 'GM', label: 'Gambia', phone: '220' },
  { code: 'GN', label: 'Guinea', phone: '224' },
  { code: 'GP', label: 'Guadeloupe', phone: '590' },
  { code: 'GQ', label: 'Equatorial Guinea', phone: '240' },
  { code: 'GR', label: 'Greece', phone: '30' },
  {
    code: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  { code: 'GT', label: 'Guatemala', phone: '502' },
  { code: 'GU', label: 'Guam', phone: '1-671' },
  { code: 'GW', label: 'Guinea-Bissau', phone: '245' },
  { code: 'GY', label: 'Guyana', phone: '592' },
  { code: 'HK', label: 'Hong Kong', phone: '852' },
  {
    code: 'HM',
    label: 'Heard Island and McDonald Islands',
    phone: '672',
  },
  { code: 'HN', label: 'Honduras', phone: '504' },
  { code: 'HR', label: 'Croatia', phone: '385' },
  { code: 'HT', label: 'Haiti', phone: '509' },
  { code: 'HU', label: 'Hungary', phone: '36' },
  { code: 'ID', label: 'Indonesia', phone: '62' },
  { code: 'IE', label: 'Ireland', phone: '353' },
  { code: 'IL', label: 'Israel', phone: '972' },
  { code: 'IM', label: 'Isle of Man', phone: '44' },
  { code: 'IN', label: 'India', phone: '91' },
  {
    code: 'IO',
    label: 'British Indian Ocean Territory',
    phone: '246',
  },
  { code: 'IQ', label: 'Iraq', phone: '964' },
  {
    code: 'IR',
    label: 'Iran, Islamic Republic of',
    phone: '98',
  },
  { code: 'IS', label: 'Iceland', phone: '354' },
  { code: 'IT', label: 'Italy', phone: '39' },
  { code: 'JE', label: 'Jersey', phone: '44' },
  { code: 'JM', label: 'Jamaica', phone: '1-876' },
  { code: 'JO', label: 'Jordan', phone: '962' },
  {
    code: 'JP',
    label: 'Japan',
    phone: '81',
    suggested: true,
  },
  { code: 'KE', label: 'Kenya', phone: '254' },
  { code: 'KG', label: 'Kyrgyzstan', phone: '996' },
  { code: 'KH', label: 'Cambodia', phone: '855' },
  { code: 'KI', label: 'Kiribati', phone: '686' },
  { code: 'KM', label: 'Comoros', phone: '269' },
  {
    code: 'KN',
    label: 'Saint Kitts and Nevis',
    phone: '1-869',
  },
  {
    code: 'KP',
    label: "Korea, Democratic People's Republic of",
    phone: '850',
  },
  { code: 'KR', label: 'Korea, Republic of', phone: '82' },
  { code: 'KW', label: 'Kuwait', phone: '965' },
  { code: 'KY', label: 'Cayman Islands', phone: '1-345' },
  { code: 'KZ', label: 'Kazakhstan', phone: '7' },
  {
    code: 'LA',
    label: "Lao People's Democratic Republic",
    phone: '856',
  },
  { code: 'LB', label: 'Lebanon', phone: '961' },
  { code: 'LC', label: 'Saint Lucia', phone: '1-758' },
  { code: 'LI', label: 'Liechtenstein', phone: '423' },
  { code: 'LK', label: 'Sri Lanka', phone: '94' },
  { code: 'LR', label: 'Liberia', phone: '231' },
  { code: 'LS', label: 'Lesotho', phone: '266' },
  { code: 'LT', label: 'Lithuania', phone: '370' },
  { code: 'LU', label: 'Luxembourg', phone: '352' },
  { code: 'LV', label: 'Latvia', phone: '371' },
  { code: 'LY', label: 'Libya', phone: '218' },
  { code: 'MA', label: 'Morocco', phone: '212' },
  { code: 'MC', label: 'Monaco', phone: '377' },
  {
    code: 'MD',
    label: 'Moldova, Republic of',
    phone: '373',
  },
  { code: 'ME', label: 'Montenegro', phone: '382' },
  {
    code: 'MF',
    label: 'Saint Martin (French part)',
    phone: '590',
  },
  { code: 'MG', label: 'Madagascar', phone: '261' },
  { code: 'MH', label: 'Marshall Islands', phone: '692' },
  {
    code: 'MK',
    label: 'Macedonia, the Former Yugoslav Republic of',
    phone: '389',
  },
  { code: 'ML', label: 'Mali', phone: '223' },
  { code: 'MM', label: 'Myanmar', phone: '95' },
  { code: 'MN', label: 'Mongolia', phone: '976' },
  { code: 'MO', label: 'Macao', phone: '853' },
  {
    code: 'MP',
    label: 'Northern Mariana Islands',
    phone: '1-670',
  },
  { code: 'MQ', label: 'Martinique', phone: '596' },
  { code: 'MR', label: 'Mauritania', phone: '222' },
  { code: 'MS', label: 'Montserrat', phone: '1-664' },
  { code: 'MT', label: 'Malta', phone: '356' },
  { code: 'MU', label: 'Mauritius', phone: '230' },
  { code: 'MV', label: 'Maldives', phone: '960' },
  { code: 'MW', label: 'Malawi', phone: '265' },
  { code: 'MX', label: 'Mexico', phone: '52' },
  { code: 'MY', label: 'Malaysia', phone: '60' },
  { code: 'MZ', label: 'Mozambique', phone: '258' },
  { code: 'NA', label: 'Namibia', phone: '264' },
  { code: 'NC', label: 'New Caledonia', phone: '687' },
  { code: 'NE', label: 'Niger', phone: '227' },
  { code: 'NF', label: 'Norfolk Island', phone: '672' },
  { code: 'NG', label: 'Nigeria', phone: '234' },
  { code: 'NI', label: 'Nicaragua', phone: '505' },
  { code: 'NL', label: 'Netherlands', phone: '31' },
  { code: 'NO', label: 'Norway', phone: '47' },
  { code: 'NP', label: 'Nepal', phone: '977' },
  { code: 'NR', label: 'Nauru', phone: '674' },
  { code: 'NU', label: 'Niue', phone: '683' },
  { code: 'NZ', label: 'New Zealand', phone: '64' },
  { code: 'OM', label: 'Oman', phone: '968' },
  { code: 'PA', label: 'Panama', phone: '507' },
  { code: 'PE', label: 'Peru', phone: '51' },
  { code: 'PF', label: 'French Polynesia', phone: '689' },
  { code: 'PG', label: 'Papua New Guinea', phone: '675' },
  { code: 'PH', label: 'Philippines', phone: '63' },
  { code: 'PK', label: 'Pakistan', phone: '92' },
  { code: 'PL', label: 'Poland', phone: '48' },
  {
    code: 'PM',
    label: 'Saint Pierre and Miquelon',
    phone: '508',
  },
  { code: 'PN', label: 'Pitcairn', phone: '870' },
  { code: 'PR', label: 'Puerto Rico', phone: '1' },
  {
    code: 'PS',
    label: 'Palestine, State of',
    phone: '970',
  },
  { code: 'PT', label: 'Portugal', phone: '351' },
  { code: 'PW', label: 'Palau', phone: '680' },
  { code: 'PY', label: 'Paraguay', phone: '595' },
  { code: 'QA', label: 'Qatar', phone: '974' },
  { code: 'RE', label: 'Reunion', phone: '262' },
  { code: 'RO', label: 'Romania', phone: '40' },
  { code: 'RS', label: 'Serbia', phone: '381' },
  { code: 'RU', label: 'Russian Federation', phone: '7' },
  { code: 'RW', label: 'Rwanda', phone: '250' },
  { code: 'SA', label: 'Saudi Arabia', phone: '966' },
  { code: 'SB', label: 'Solomon Islands', phone: '677' },
  { code: 'SC', label: 'Seychelles', phone: '248' },
  { code: 'SD', label: 'Sudan', phone: '249' },
  { code: 'SE', label: 'Sweden', phone: '46' },
  { code: 'SG', label: 'Singapore', phone: '65' },
  { code: 'SH', label: 'Saint Helena', phone: '290' },
  { code: 'SI', label: 'Slovenia', phone: '386' },
  {
    code: 'SJ',
    label: 'Svalbard and Jan Mayen',
    phone: '47',
  },
  { code: 'SK', label: 'Slovakia', phone: '421' },
  { code: 'SL', label: 'Sierra Leone', phone: '232' },
  { code: 'SM', label: 'San Marino', phone: '378' },
  { code: 'SN', label: 'Senegal', phone: '221' },
  { code: 'SO', label: 'Somalia', phone: '252' },
  { code: 'SR', label: 'Suriname', phone: '597' },
  { code: 'SS', label: 'South Sudan', phone: '211' },
  {
    code: 'ST',
    label: 'Sao Tome and Principe',
    phone: '239',
  },
  { code: 'SV', label: 'El Salvador', phone: '503' },
  {
    code: 'SX',
    label: 'Sint Maarten (Dutch part)',
    phone: '1-721',
  },
  {
    code: 'SY',
    label: 'Syrian Arab Republic',
    phone: '963',
  },
  { code: 'SZ', label: 'Swaziland', phone: '268' },
  {
    code: 'TC',
    label: 'Turks and Caicos Islands',
    phone: '1-649',
  },
  { code: 'TD', label: 'Chad', phone: '235' },
  {
    code: 'TF',
    label: 'French Southern Territories',
    phone: '262',
  },
  { code: 'TG', label: 'Togo', phone: '228' },
  { code: 'TH', label: 'Thailand', phone: '66' },
  { code: 'TJ', label: 'Tajikistan', phone: '992' },
  { code: 'TK', label: 'Tokelau', phone: '690' },
  { code: 'TL', label: 'Timor-Leste', phone: '670' },
  { code: 'TM', label: 'Turkmenistan', phone: '993' },
  { code: 'TN', label: 'Tunisia', phone: '216' },
  { code: 'TO', label: 'Tonga', phone: '676' },
  { code: 'TR', label: 'Turkey', phone: '90' },
  {
    code: 'TT',
    label: 'Trinidad and Tobago',
    phone: '1-868',
  },
  { code: 'TV', label: 'Tuvalu', phone: '688' },
  {
    code: 'TW',
    label: 'Taiwan, Republic of China',
    phone: '886',
  },
  {
    code: 'TZ',
    label: 'United Republic of Tanzania',
    phone: '255',
  },
  { code: 'UA', label: 'Ukraine', phone: '380' },
  { code: 'UG', label: 'Uganda', phone: '256' },
  {
    code: 'US',
    label: 'United States',
    phone: '1',
    suggested: true,
  },
  { code: 'UY', label: 'Uruguay', phone: '598' },
  { code: 'UZ', label: 'Uzbekistan', phone: '998' },
  {
    code: 'VA',
    label: 'Holy See (Vatican City State)',
    phone: '379',
  },
  {
    code: 'VC',
    label: 'Saint Vincent and the Grenadines',
    phone: '1-784',
  },
  { code: 'VE', label: 'Venezuela', phone: '58' },
  {
    code: 'VG',
    label: 'British Virgin Islands',
    phone: '1-284',
  },
  {
    code: 'VI',
    label: 'US Virgin Islands',
    phone: '1-340',
  },
  { code: 'VN', label: 'Vietnam', phone: '84' },
  { code: 'VU', label: 'Vanuatu', phone: '678' },
  { code: 'WF', label: 'Wallis and Futuna', phone: '681' },
  { code: 'WS', label: 'Samoa', phone: '685' },
  { code: 'XK', label: 'Kosovo', phone: '383' },
  { code: 'YE', label: 'Yemen', phone: '967' },
  { code: 'YT', label: 'Mayotte', phone: '262' },
  { code: 'ZA', label: 'South Africa', phone: '27' },
  { code: 'ZM', label: 'Zambia', phone: '260' },
  { code: 'ZW', label: 'Zimbabwe', phone: '263' },
];